"""initial

Revision ID: b013bdd02aa0
Revises: 
Create Date: 2022-12-23 20:03:14.104111

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b013bdd02aa0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["user_id"])
    op.create_foreign_key(None, "expenses", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_table("users")
    # ### end Alembic commands ###
